[package]
name = "GLUE"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
content_inspector = "0.2.4"
glob = "0.3.2"
ignore = "0.4.23"
